version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.13
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  api:
    working_dir: /usr/app
    image: "node:18.12.1"
    links:
      - mongodb
    volumes:
      - ./dist:/usr/app/dist
      - ./package.json:/usr/app/package.json
    command: bash -c "npm install --omit=dev && npm start"
    ports:
      - "8080:8080"
