version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.13
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  api:
    build: .
    image: "typescript-clean-api"
    links:
      - mongodb
    volumes:
      - ./dist:/usr/app/dist
    command: npm start
    ports:
      - "8080:8080"
